version: '3.8'

services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - '443:443'
      # - '4200:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/browser:/usr/share/nginx/html
      - ./selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./selfsigned.key:/etc/nginx/ssl/selfsigned.key
